### ISSUE TITLE
Short UUID compatibility with other libraries

### ISSUE THREAD

**Issue by kanes115** [gpedic/shortuuid#5]
There seem to be a compatibility issue with other short UUID (base57) tools out there. I've tried to compare the results of this library with results of the [JS library](https://www.npmjs.com/package/short-uuid) and a [python one](https://pypi.org/project/shortuuid/) and the results are the same between them but not the same with this elixir library.

Elixir example:
```
iex(6)> "91f10722-c263-4752-9ecf-53fde67c4028" |> ShortUUID.encode()
{:ok, "9JwfvPdZY9QKG6BPovn5yT"}
```

While JS and python libs yield:
`Ty5nvoPB6GKQ9YZdPvfwJ9`

Note I'm using the same alphabet of `23456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz`.

In the docs you specify that there **should** be no difference between other short uuid tools and this one so maybe this is something worth looking into. In our case it makes it hard for the JS app to communicate with our elixir server.

Thanks in advance!

**Comment by gpedic** [comment]
The problem is that those other libraries changed their implementation to preserve the position of the most significant bit in the encoded version, in other words they reverse the string now. I haven't used any of those other non elixir libraries in ages so was not aware of the change. I'm working on a 3.0.0 release and might include this too but I don't quite like how breaking of a change it would be to make this new behaviour the default.

https://github.com/skorokithakis/shortuuid/pull/36

```
iex> "91f10722-c263-4752-9ecf-53fde67c4028" |> ShortUUID.encode!() |> String.reverse()
"Ty5nvoPB6GKQ9YZdPvfwJ9"

iex> "Ty5nvoPB6GKQ9YZdPvfwJ9" |> String.reverse() |> ShortUUID.decode!()
"91f10722-c263-4752-9ecf-53fde67c4028"
```

Thanks for taking the time to open an issue, I will try to address it somehow.
